export const BOOK_CATEGORIES_API= 'http://localhost:8000/book_categories'

export const GET_BOOK_CATEGORIES = "GET_BOOK_CATEGORIES"


export const BOOK_CAT_CRUD_OPP_REQUEST = 'BOOK_CAT_CRUD_OPP_REQUEST'

export const BOOK_CAT_CRUD_OPP_SUCCESS = 'BOOK_CAT_CRUD_OPP_SUCCESS'

export const BOOK_CAT_CRUD_OPP_FAILURE = 'BOOK_CAT_CRUD_OPP_FAILURE'
